### PR TITLE
Setup github actions for JDK 17

### PR DESCRIPTION
**Pull request by mslowiak**
Closes: #38
@josdem

### CODE REVIEW

**Comment by mslowiak** [comment]
@josdem Bumped to JDK 17

**Review by josdem — COMMENTED** [review]
@mslowiak  As far as I remember we need to setup mongodb database before running tests, this is what I did using travis. https://github.com/josdem/jugoterapia-webflux/blob/master/.travis.yml

**Comment by mslowiak** [comment]
@josdem 
Can you elaborate more which tests are using the database?
Can this database be setup with testcontainers?

**Comment by josdem** [comment]
> @josdem 
> Can you elaborate more which tests are using the database?
> Can this database be setup with testcontainers?

Hi @mslowiak:
- All controller tests required BD 
- Not sure if we can use testcontainers, let me explore that option. Also I will explore to set up a Mongo DB using GitHub actions.

**Comment by josdem** [comment]
GitHub actions integrated: https://github.com/josdem/jugoterapia-webflux/actions/runs/8324277838

**Pull request closed without merging**
